# Generated by Django 5.2.3 on 2026-03-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('event_date', models.DateField()),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('engagement', 'Engagement'), ('eid', 'Eid Celebration'), ('christmas', 'Christmas'), ('corporate', 'Corporate Event'), ('other', 'Other')], max_length=20)),
                ('rental_duration', models.CharField(choices=[('3days', '3 Days'), ('5days', '5 Days'), ('7days', '7 Days'), ('10days', '10 Days'), ('custom', 'Custom Duration')], max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Wedding', 'Wedding'), ('Birthday', 'Birthday'), ('Christmas', 'Christmas'), ('Eid', 'Eid'), ('Corporate', 'Corporate')], max_length=50)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='hero/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Wedding', 'Wedding'), ('Birthday', 'Birthday'), ('Christmas', 'Christmas'), ('Eid', 'Eid'), ('Corporate', 'Corporate')], max_length=50)),
                ('image', models.ImageField(upload_to='products/')),
                ('description', models.TextField()),
                ('price_3days', models.PositiveIntegerField(verbose_name='Price (3 Days)')),
                ('price_5days', models.PositiveIntegerField(verbose_name='Price (5 Days)')),
                ('price_7days', models.PositiveIntegerField(verbose_name='Price (7 Days)')),
                ('price_10days', models.PositiveIntegerField(verbose_name='Price (10 Days)')),
                ('spec_lights', models.CharField(max_length=100, verbose_name='Lights')),
                ('spec_coverage', models.CharField(max_length=100, verbose_name='Coverage')),
                ('spec_style', models.CharField(max_length=100, verbose_name='Style')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_type', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField(default=5)),
                ('testimonial', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='testimonials/')),
            ],
        ),
    ]
