# Generated by Django 5.2.3 on 2026-03-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinquiry',
            name='rental_duration',
            field=models.CharField(choices=[('1day', '1 Day'), ('2days', '2 Days'), ('3days', '3 Days'), ('5days', '5 Days'), ('7days', '7 Days'), ('10days', '10 Days'), ('custom', 'Custom Duration')], max_length=20),
        ),
    ]
